# Generated by Django 6.0.5 on 2026-08-09 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_number', models.CharField(max_length=50, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('expected_checkout_date', models.DateField()),
                ('actual_checkout_date', models.DateField(blank=True, null=True)),
                ('actual_checkout_time', models.TimeField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('room_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='FIXED', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], default='CHECKED_IN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stays', to=settings.AUTH_USER_MODEL)),
                ('primary_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='customers.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='StayGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('Aadhaar', 'Aadhaar'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Driving Licence', 'Driving Licence'), ('Voter ID', 'Voter ID'), ('Other', 'Other')], max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='guests/documents/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guests/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_stays', to='customers.customer')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='stays.stay')),
            ],
        ),
    ]
