# Generated by Django 6.0.5 on 2026-08-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_stay_expected_checkout_time_alter_stay_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayguest',
            name='id_document_back',
            field=models.FileField(blank=True, null=True, upload_to='guests/documents/'),
        ),
    ]
