# Generated by Django 6.0.5 on 2026-08-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0003_stayguest_id_document_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
