# Generated by Django 6.0.5 on 2026-08-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_remove_settings_daily_petty_cash_cap_and_more'),
        ('stays', '0004_stay_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='settings_app.property'),
        ),
    ]
