# Generated by Django 6.0.5 on 2026-09-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0005_stay_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='chargeable_nights',
            field=models.PositiveIntegerField(blank=True, help_text='Explicitly billed room nights (e.g. bounded override for early check-in or late checkout)', null=True),
        ),
    ]
