# Generated by Django 6.0.5 on 2026-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0007_historicalstay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstay',
            name='check_in_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstay',
            name='expected_checkout_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstay',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], db_index=True, default='CHECKED_IN', max_length=20),
        ),
        migrations.AlterField(
            model_name='stay',
            name='check_in_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='expected_checkout_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], db_index=True, default='CHECKED_IN', max_length=20),
        ),
    ]
