# Generated by Django 6.0.5 on 2026-08-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_id_document_back_customerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advance_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
