# Generated by Django 6.0.5 on 2026-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_historicalcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
