# Generated by Django 6.0.5 on 2026-08-26 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftexpense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftexpense',
            name='is_manager_approved',
            field=models.BooleanField(default=False),
        ),
    ]
