# Generated by Django 6.0.5 on 2026-08-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shiftexpense_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing'), ('PENDING_APPROVAL', 'Pending Manager Approval'), ('PENDING_REVIEW', 'Stale - Pending Manager Review'), ('CLOSED', 'Closed'), ('FORCED_CLOSED', 'Admin Force Closed')], db_index=True, default='OPEN', max_length=30),
        ),
    ]
