# Generated by Django 6.0.5 on 2026-08-26 03:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_shift_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Front Desk Till #1', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='e.g. POS-MAIN-01', max_length=30, unique=True)),
                ('location', models.CharField(blank=True, help_text='e.g. Reception Lobby', max_length=100, null=True)),
                ('default_float', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_shared_users', models.BooleanField(default=False, help_text='Allow multiple cashiers to operate simultaneously')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='cash_drawer',
            field=models.ForeignKey(blank=True, help_text='Physical POS Register / Cash Drawer assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifts.cashdrawer'),
        ),
    ]
