# Generated by Django 6.0.5 on 2026-08-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_remove_settings_daily_petty_cash_cap_and_more'),
        ('shifts', '0004_cashdrawer_shift_cash_drawer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrawer',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='settings_app.property'),
        ),
        migrations.AddField(
            model_name='shift',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='settings_app.property'),
        ),
        migrations.AlterField(
            model_name='cashdrawer',
            name='code',
            field=models.CharField(db_index=True, help_text='e.g. POS-MAIN-01', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='cashdrawer',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='unique_property_drawer_code'),
        ),
    ]
