# Generated by Django 6.0.5 on 2026-09-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_shift_updated_by_shiftcashadjustment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifthandover',
            name='is_opening_handover',
            field=models.BooleanField(default=False, help_text='True if this handover served as the opening float for to_shift'),
        ),
    ]
