# Generated by Django 6.0.5 on 2026-08-13 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracharge',
            name='charge_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
