# Generated by Django 6.0.5 on 2026-08-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_extracharge_charge_date'),
        ('customers', '0003_customer_advance_credit'),
        ('stays', '0003_stayguest_id_document_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stays.stay'),
        ),
    ]
