# Generated by Django 6.0.5 on 2026-09-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_payment_created_by_payment_updated_at_and_more'),
        ('settings_app', '0011_alter_subscriptionplan_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chargetype',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='unique_property_charge_type_name'),
        ),
    ]
