# Generated by Django 6.0.5 on 2026-09-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Contact Name')),
                ('property_name', models.CharField(max_length=200, verbose_name='Property / Lodge Name')),
                ('room_count', models.PositiveIntegerField(default=15, verbose_name='Total Rooms')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City / Location')),
                ('service_interest', models.CharField(choices=[('all', 'Full Cloud PMS Suite (All Features)'), ('frontdesk', 'Front-Desk & Stay Lifecycle Engine'), ('calendar', 'Interactive Room Tape Chart & Calendar'), ('shifts', 'Cash Drawer & Shift Handover Audit'), ('catalogue', 'Dynamic Room QR Catalogue & Room Service'), ('billing', 'Split GST Billing & 80mm Thermal Invoicing'), ('chain', 'Multi-Branch Hotel Chain Management')], default='all', max_length=50, verbose_name='Primary Solution Interest')),
                ('message', models.TextField(blank=True, verbose_name='Inquiry Details / Specific Requirements')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Followed Up / Contacted')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Internal Admin Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
            ],
            options={
                'verbose_name': 'Demo & Lead Inquiry',
                'verbose_name_plural': 'Demo & Lead Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
