# Generated by Django 6.0.5 on 2026-08-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(default='Lodge Management System', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lodge/')),
                ('address', models.TextField(default='123 Main Street, Station Road, City')),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('email', models.EmailField(default='info@lodgemanagement.com', max_length=254)),
                ('website', models.CharField(default='www.lodgemanagement.com', max_length=100)),
                ('gst_number', models.CharField(default='27AAAAA0000A1Z5', max_length=50)),
                ('currency', models.CharField(default='₹', max_length=10)),
                ('tax_enabled', models.BooleanField(default=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('default_checkin_time', models.TimeField(default='12:00:00')),
                ('default_checkout_time', models.TimeField(default='11:00:00')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('booking_prefix', models.CharField(default='BK-', max_length=20)),
                ('stay_prefix', models.CharField(default='STAY-', max_length=20)),
            ],
        ),
    ]
