# Generated by Django 6.0.5 on 2026-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='allow_checkout_with_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_advance_booking_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_receptionist_discount_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='min_stay_duration_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='settings',
            name='require_guest_id_on_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='require_guest_id_on_checkin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='room_turnaround_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
