# Generated by Django 6.0.5 on 2026-08-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_settings_allow_checkout_with_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notify_shift_close_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='notify_shift_close_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='shift_alert_emails',
            field=models.CharField(blank=True, default='', help_text='Comma-separated manager emails for shift alerts', max_length=500),
        ),
        migrations.AddField(
            model_name='settings',
            name='shift_alert_phones',
            field=models.CharField(blank=True, default='', help_text='Comma-separated mobile numbers with country code for WhatsApp alerts', max_length=500),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, default='', help_text='WhatsApp Gateway Token / Key (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_api_url',
            field=models.URLField(blank=True, help_text='Custom WhatsApp Gateway API URL (optional)', null=True),
        ),
    ]
