# Generated by Django 6.0.5 on 2026-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_settings_notify_shift_close_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_blind_till_closing',
            field=models.BooleanField(default=False, help_text='Hide expected cash ledger from receptionists during shift closing'),
        ),
    ]
