# Generated by Django 6.0.5 on 2026-08-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_settings_enable_blind_till_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='daily_petty_cash_cap',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Daily total petty cash disbursement cap', max_digits=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='manager_override_pin',
            field=models.CharField(default='1234', help_text='Manager PIN for approving high expenses', max_length=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_cash_expense_without_approval',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Max single petty cash expense without manager PIN', max_digits=10),
        ),
    ]
