# Generated by Django 6.0.5 on 2026-08-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_settings_daily_petty_cash_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='auto_rollover_daily_till',
            field=models.BooleanField(default=True, help_text='Automatically roll over physical cash drawer daily in single-operator mode'),
        ),
        migrations.AddField(
            model_name='settings',
            name='shift_operation_mode',
            field=models.CharField(choices=[('STRICT_SHIFT', 'Multi-Cashier Shift Mode'), ('SINGLE_OPERATOR', 'Single-User / Owner-Managed Mode')], default='STRICT_SHIFT', help_text='Operating mode: Strict Shift-wise vs Single-Operator / Owner Mode', max_length=30),
        ),
    ]
