# Generated by Django 6.0.5 on 2026-08-26 05:16

import apps.settings_app.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_settings_auto_rollover_daily_till_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('gstin', models.CharField(blank=True, default='', max_length=50)),
                ('total_rooms', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('FREE_TRIAL', 'Free Trial (14 Days)'), ('STARTER', 'Starter (Up to 15 Rooms)'), ('GROWTH', 'Growth (Up to 40 Rooms)'), ('ENTERPRISE', 'Enterprise (Unlimited Rooms)')], max_length=50, unique=True)),
                ('max_rooms', models.IntegerField(default=15)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
                ('price_annually', models.DecimalField(decimal_places=2, default=9999.0, max_digits=10)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('LIFETIME', 'Lifetime / Custom')], default='ANNUAL', max_length=20)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField()),
                ('is_paid', models.BooleanField(default=True)),
                ('license_key', models.CharField(default=apps.settings_app.models.generate_crypto_license_key, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lodge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='settings_app.property')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='settings_app.subscriptionplan')),
            ],
        ),
    ]
