# Generated by Django 6.0.5 on 2026-08-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_property_subscriptionplan_propertysubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='daily_petty_cash_cap',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='max_cash_expense_without_approval',
        ),
        migrations.AddField(
            model_name='settings',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='settings_app.property'),
        ),
    ]
