# Generated by Django 6.0.5 on 2026-09-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_remove_settings_daily_petty_cash_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parent_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='settings_app.property'),
        ),
        migrations.AddField(
            model_name='propertysubscription',
            name='billing_amount',
            field=models.DecimalField(decimal_places=2, default=9999.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertysubscription',
            name='payment_status',
            field=models.CharField(default='PAID', max_length=20),
        ),
    ]
