# Generated by Django 6.0.5 on 2026-09-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_property_parent_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysubscription',
            name='license_key',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
