# Generated by Django 6.0.5 on 2026-09-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0010_alter_propertysubscription_license_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
