# Generated by Django 6.0.5 on 2026-09-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0011_alter_subscriptionplan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='operation_mode',
            field=models.CharField(choices=[('SHIFT_WISE', 'Shift-Wise (Multi-Staff Shifts)'), ('SINGLE_OWNER', 'Single Owner (No Shifts / Direct)')], default='SHIFT_WISE', help_text='Operational mode set by platform developer: Shift-Wise vs Single Owner', max_length=30),
        ),
    ]
