# Generated by Django 6.0.5 on 2026-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0012_property_operation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='daily_petty_cash_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=5000.0, help_text='Maximum aggregate petty cash allowed per day/shift across property', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_cash_expense_without_approval',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, help_text='Maximum cash expense without requiring manager PIN authorization', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.TextField(blank=True, default='123 Main Street, Station Road, City'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='booking_prefix',
            field=models.CharField(blank=True, default='BK-', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(blank=True, default='₹', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(blank=True, default='info@lodgemanagement.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='settings',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV-', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='manager_override_pin',
            field=models.CharField(blank=True, default='1234', help_text='Manager PIN for approving high expenses', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(blank=True, default='+91 98765 43210', max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='stay_prefix',
            field=models.CharField(blank=True, default='STAY-', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='website',
            field=models.CharField(blank=True, default='www.lodgemanagement.com', max_length=100),
        ),
    ]
