# Generated by Django 6.0.5 on 2026-09-30 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_check_in_date_and_more'),
        ('customers', '0006_alter_customer_mobile_and_more'),
        ('settings_app', '0013_settings_daily_petty_cash_cap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp_booking_enabled',
            field=models.BooleanField(default=True, help_text='Enable WhatsApp message on booking creation'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_booking_template',
            field=models.TextField(blank=True, default='Hello {{guest_name}},\n\nYour booking at {{property_name}} has been confirmed.\n\nBooking: {{booking_number}}\nRoom: {{room_number}}\nCheck-in: {{check_in_date}} {{check_in_time}}\nCheck-out: {{check_out_date}}\nGuests: {{guest_count}}\n\nAdvance Paid: ₹{{advance_paid}}\nBalance: ₹{{balance_amount}}\n\nThank you!\n{{property_name}}', help_text='Custom message template for booking confirmation'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_checkin_enabled',
            field=models.BooleanField(default=True, help_text='Enable WhatsApp message on check-in'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_checkin_template',
            field=models.TextField(blank=True, default='Hello {{guest_name}},\n\nWelcome to {{property_name}}! Your check-in is complete.\n\nRoom: {{room_number}}\nCheck-out: {{check_out_date}} {{check_out_time}}\nAmount Paid: ₹{{amount_paid}}\nBalance: ₹{{balance_amount}}\n\nWe wish you a comfortable stay!\n\n{{property_name}}', help_text='Custom message template for check-in welcome'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_checkout_enabled',
            field=models.BooleanField(default=True, help_text='Enable WhatsApp message on check-out'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_checkout_template',
            field=models.TextField(blank=True, default='Hello {{guest_name}},\n\nThank you for staying at {{property_name}}!\n\nBooking: {{booking_number}}\nRoom: {{room_number}}\nTotal Amount: ₹{{grand_total}}\nAmount Paid: ₹{{total_paid}}\nBalance: ₹{{balance_amount}}\n\nWe appreciate your visit and look forward to welcoming you again.\n\nThank you!', help_text='Custom message template for check-out thank you'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_default_country_code',
            field=models.CharField(blank=True, default='+91', help_text='Default international country code (e.g. +91)', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='Master toggle to enable customer WhatsApp messaging'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_payment_enabled',
            field=models.BooleanField(default=True, help_text='Enable WhatsApp message on payment received'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_payment_template',
            field=models.TextField(blank=True, default='Hello {{guest_name}},\n\nWe have received your payment of ₹{{payment_amount}}.\n\nBooking: {{booking_number}}\nTotal Paid: ₹{{total_paid}}\nBalance Due: ₹{{balance_amount}}\n\nThank you!\n{{property_name}}', help_text='Custom message template for payment receipt'),
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=150)),
                ('mobile', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(default='Prepared / Opened', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='customers.customer')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='settings_app.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
