# Generated by Django 6.0.5 on 2026-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0014_settings_whatsapp_booking_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp_cancellation_enabled',
            field=models.BooleanField(default=True, help_text='Enable WhatsApp message on booking cancellation'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_cancellation_template',
            field=models.TextField(blank=True, default='Hello {{guest_name}},\n\nYour booking at {{property_name}} has been cancelled.\n\nBooking: {{booking_number}}\nRoom: {{room_number}}\nCheck-in Date: {{check_in_date}}\nCheck-out Date: {{check_out_date}}\n\nIf you have any questions or need to re-book, please contact us at {{property_phone}}.\n\nThank you,\n{{property_name}}', help_text='Custom message template for booking cancellation'),
        ),
    ]
