# Generated by Django 6.0.5 on 2026-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0015_settings_whatsapp_cancellation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp_extra_charge_enabled',
            field=models.BooleanField(default=True, help_text='Enable WhatsApp message when extra charge is added'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_extra_charge_template',
            field=models.TextField(blank=True, default='Hello {{guest_name}},\n\nAn extra charge has been added to your stay at {{property_name}}.\n\nStay: {{booking_number}}\nRoom: {{room_number}}\nCharge: {{charge_description}}\nAmount: ₹{{charge_amount}}\nTotal Extra Charges: ₹{{total_extra_charges}}\nCurrent Balance Due: ₹{{balance_amount}}\n\nThank you!\n{{property_name}}', help_text='Custom message template for extra charges'),
        ),
    ]
