# Generated by Django 6.0.5 on 2026-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0016_settings_whatsapp_extra_charge_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp_auto_close_tab',
            field=models.BooleanField(default=True, help_text='Automatically close temporary tab after opening WhatsApp Desktop app'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_close_delay_seconds',
            field=models.PositiveSmallIntegerField(default=2, help_text='Auto-close countdown delay in seconds'),
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_open_mode',
            field=models.CharField(blank=True, default='app_autoclose', help_text="Preferred opening mode: 'app_autoclose', 'app_direct', 'web', 'universal'", max_length=50),
        ),
    ]
