# Generated by Django 6.0.5 on 2026-10-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0017_settings_whatsapp_auto_close_tab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle to enable customer WhatsApp messaging'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='whatsapp_open_mode',
            field=models.CharField(blank=True, default='universal', help_text="Preferred opening mode: 'universal', 'web', 'app_autoclose', 'app_direct'", max_length=50),
        ),
    ]
