# Generated by Django 6.0.5 on 2026-09-12 01:35

import apps.catalogue.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0005_historicalroomtype_catalogue_badge_and_more'),
        ('settings_app', '0013_settings_daily_petty_cash_cap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_mobile', models.CharField(max_length=30)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Contacted / In Progress'), ('CONVERTED', 'Converted to Booking'), ('DECLINED', 'Declined / Closed')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='settings_app.property')),
                ('requested_room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue/rooms/')),
                ('caption', models.CharField(blank=True, default='', max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['display_order', '-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HotelCatalogueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this hotel/branch catalogue is publicly accessible')),
                ('hero_headline', models.CharField(blank=True, default='', help_text='Custom banner headline (defaults to hotel name if blank)', max_length=200)),
                ('hero_tagline', models.CharField(blank=True, default='', help_text='Subtitle or marketing tagline', max_length=250)),
                ('about_text', models.TextField(blank=True, default='', help_text='Detailed story or welcome message')),
                ('hero_banner', models.ImageField(blank=True, null=True, upload_to='catalogue/banners/')),
                ('accent_theme', models.CharField(choices=[('BLUE', 'Royal Blue'), ('EMERALD', 'Emerald Luxury'), ('GOLD', 'Golden Amber'), ('ROSE', 'Rose Elegance'), ('SLATE', 'Modern Dark Slate')], default='BLUE', max_length=20)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('address_override', models.TextField(blank=True, default='')),
                ('city_override', models.CharField(blank=True, default='', max_length=100)),
                ('google_maps_embed_url', models.TextField(blank=True, default='', help_text='Google Maps iframe embed src URL')),
                ('google_maps_directions_url', models.URLField(blank=True, default='', help_text='Shareable Google Maps link for navigation')),
                ('landmark', models.CharField(blank=True, default='', max_length=200)),
                ('facilities_json', models.JSONField(blank=True, default=apps.catalogue.models.default_facilities_list)),
                ('check_in_time', models.CharField(default='12:00 PM', max_length=20)),
                ('check_out_time', models.CharField(default='11:00 AM', max_length=20)),
                ('cancellation_policy', models.TextField(blank=True, default="Free cancellation up to 24 hours prior to check-in. Cancellations after that are subject to one night's charge.")),
                ('house_rules', models.TextField(blank=True, default='Valid government ID required at check-in (Aadhaar / Passport / Voter ID). Couples and families welcome.')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='settings_app.property')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property',), name='unique_catalogue_property')],
            },
        ),
    ]
