# Generated by Django 6.0.5 on 2026-09-13 03:04

import apps.catalogue.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('settings_app', '0013_settings_daily_petty_cash_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcatalogueconfig',
            name='about_title',
            field=models.CharField(blank=True, default='Our Heritage & Signature Hospitality', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelcatalogueconfig',
            name='direct_privileges_json',
            field=models.JSONField(blank=True, default=apps.catalogue.models.default_privileges_list),
        ),
        migrations.AddField(
            model_name='hotelcatalogueconfig',
            name='faqs_json',
            field=models.JSONField(blank=True, default=apps.catalogue.models.default_faqs_list),
        ),
        migrations.AddField(
            model_name='hotelcatalogueconfig',
            name='nearby_places_json',
            field=models.JSONField(blank=True, default=apps.catalogue.models.default_nearby_places),
        ),
        migrations.AddField(
            model_name='hotelcatalogueconfig',
            name='rating_summary_json',
            field=models.JSONField(blank=True, default=apps.catalogue.models.default_rating_summary),
        ),
        migrations.AddField(
            model_name='hotelcatalogueconfig',
            name='reviews_json',
            field=models.JSONField(blank=True, default=apps.catalogue.models.default_reviews_list),
        ),
        migrations.AddField(
            model_name='hotelcatalogueconfig',
            name='show_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelcatalogueconfig',
            name='stats_json',
            field=models.JSONField(blank=True, default=apps.catalogue.models.default_stats_list),
        ),
        migrations.CreateModel(
            name='HotelGalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue/gallery/')),
                ('caption', models.CharField(blank=True, default='', max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='settings_app.property')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
