import logging
import threading
import requests
from django.core.mail import send_mail
from django.conf import settings as django_settings
from apps.settings_app.models import Settings
from apps.shifts.services import calculate_shift_financials

logger = logging.getLogger(__name__)

def build_shift_summary_text(shift, settings_obj, financials):
    lodge_name = settings_obj.lodge_name or "LODGE MANAGEMENT SYSTEM"
    diff = float(shift.cash_difference or 0.0)
    is_shortage = diff < -0.01
    is_excess = diff > 0.01
    is_balanced = not is_shortage and not is_excess

    status_str = "BALANCED (₹0.00)" if is_balanced else (f"SHORTAGE (-₹{abs(diff):.2f})" if is_shortage else f"EXCESS (+₹{diff:.2f})")
    
    open_time_str = shift.opened_at.strftime('%d %b %Y, %I:%M %p') if shift.opened_at else 'N/A'
    close_time_str = shift.closed_at.strftime('%d %b %Y, %I:%M %p') if shift.closed_at else 'N/A'
    duration_mins = shift.duration_minutes
    duration_str = f"{duration_mins // 60}h {duration_mins % 60}m" if duration_mins else "N/A"

    msg = f"""🏨 *{lodge_name.upper()}* - TILL CLOSING SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━
📋 *Shift #:* {shift.shift_number}
👤 *Cashier:* {shift.user.get_full_name() or shift.user.username}
⏰ *Opened:* {open_time_str}
🔒 *Closed:* {close_time_str} ({duration_str})
━━━━━━━━━━━━━━━━━━━━━━━━━━━
💵 *PHYSICAL DRAWER CASH:*
  • Opening Float:      ₹{financials.get('opening_cash', 0):.2f}
  • Cash Collections:   +₹{financials.get('cash_collections', 0):.2f}
  • Cash Added (Float): +₹{financials.get('cash_added', 0):.2f}
  • Petty Expenses:     -₹{financials.get('cash_expenses', 0):.2f}
  • Cash Drops/Removed: -₹{financials.get('cash_removed', 0):.2f}
───────────────────────────
🏛️ *EXPECTED CASH:*    ₹{financials.get('expected_cash', 0):.2f}
💰 *ACTUAL COUNTED:*   ₹{float(shift.actual_cash or 0.0):.2f}
⚖️ *STATUS:*           *{status_str}*
"""
    if shift.difference_reason:
        msg += f"⚠️ *Reason:* {shift.difference_reason}\n"

    msg += f"""━━━━━━━━━━━━━━━━━━━━━━━━━━━
💳 *DIGITAL COLLECTIONS (Bank Accounts):*
  • UPI / QR Code:      ₹{financials.get('upi_collections', 0):.2f}
  • Card POS:           ₹{financials.get('card_collections', 0):.2f}
  • Bank Transfer:      ₹{financials.get('bank_collections', 0):.2f}
───────────────────────────
📊 *TOTAL SHIFT REVENUE:* ₹{financials.get('total_collections', 0):.2f}
━━━━━━━━━━━━━━━━━━━━━━━━━━━
🛡️ _Automated Audit Summary generated by LMS Till System._
"""
    return msg

def build_shift_summary_html(shift, settings_obj, financials):
    lodge_name = settings_obj.lodge_name or "Lodge Management System"
    diff = float(shift.cash_difference or 0.0)
    is_shortage = diff < -0.01
    is_excess = diff > 0.01
    is_balanced = not is_shortage and not is_excess

    status_color = "#16a34a" if is_balanced else ("#dc2626" if is_shortage else "#d97706")
    status_text = "BALANCED (₹0.00 Diff)" if is_balanced else (f"SHORTAGE: -₹{abs(diff):.2f}" if is_shortage else f"EXCESS: +₹{diff:.2f}")

    open_time_str = shift.opened_at.strftime('%d %b %Y, %I:%M %p') if shift.opened_at else 'N/A'
    close_time_str = shift.closed_at.strftime('%d %b %Y, %I:%M %p') if shift.closed_at else 'N/A'
    duration_mins = shift.duration_minutes
    duration_str = f"{duration_mins // 60}h {duration_mins % 60}m" if duration_mins else "N/A"

    return f"""
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #1e293b; background-color: #f8fafc; margin: 0; padding: 20px; }}
          .card {{ max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }}
          .header {{ background: linear-gradient(135deg, #09204c 0%, #1E3A8A 100%); color: #ffffff; padding: 24px; text-align: center; }}
          .body {{ padding: 24px; }}
          .table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
          .table td {{ padding: 8px 0; border-bottom: 1px solid #f1f5f9; font-size: 14px; }}
          .bold {{ font-weight: bold; }}
          .badge {{ display: inline-block; padding: 6px 12px; border-radius: 20px; font-weight: bold; font-size: 13px; color: #fff; background-color: {status_color}; }}
          .footer {{ background: #f8fafc; padding: 16px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; }}
        </style>
      </head>
      <body>
        <div class="card">
          <div class="header">
            <h2 style="margin: 0; font-size: 20px;">{lodge_name}</h2>
            <div style="font-size: 13px; opacity: 0.8; margin-top: 4px;">Official Reception Till Closing Alert</div>
          </div>
          <div class="body">
            <div style="text-align: center; margin-bottom: 16px;">
              <span class="badge">{status_text}</span>
            </div>

            <table class="table">
              <tr><td><strong>Shift Number:</strong></td><td style="text-align: right; font-family: monospace;">#{shift.shift_number}</td></tr>
              <tr><td><strong>Cashier:</strong></td><td style="text-align: right;">{shift.user.get_full_name() or shift.user.username}</td></tr>
              <tr><td><strong>Duty Session:</strong></td><td style="text-align: right;">{open_time_str} &rarr; {close_time_str} ({duration_str})</td></tr>
            </table>

            <h4 style="margin: 20px 0 8px 0; color: #1e3a8a; font-size: 14px; text-transform: uppercase;">Physical Cash Drawer Ledger</h4>
            <table class="table">
              <tr><td>(+) Opening Float:</td><td style="text-align: right; font-family: monospace;">₹{financials.get('opening_cash', 0):.2f}</td></tr>
              <tr><td>(+) Cash Receipts:</td><td style="text-align: right; font-family: monospace; color: #16a34a;">+₹{financials.get('cash_collections', 0):.2f}</td></tr>
              <tr><td>(+) Cash Added:</td><td style="text-align: right; font-family: monospace; color: #2563eb;">+₹{financials.get('cash_added', 0):.2f}</td></tr>
              <tr><td>(-) Petty Cash Expenses:</td><td style="text-align: right; font-family: monospace; color: #dc2626;">-₹{financials.get('cash_expenses', 0):.2f}</td></tr>
              <tr><td>(-) Cash Removed:</td><td style="text-align: right; font-family: monospace; color: #dc2626;">-₹{financials.get('cash_removed', 0):.2f}</td></tr>
              <tr style="background: #f8fafc; font-weight: bold;">
                <td style="padding: 10px 6px;">EXPECTED PHYSICAL CASH:</td>
                <td style="text-align: right; font-family: monospace; font-size: 16px; padding: 10px 6px;">₹{financials.get('expected_cash', 0):.2f}</td>
              </tr>
              <tr style="background: #f8fafc; font-weight: bold;">
                <td style="padding: 10px 6px;">ACTUAL PHYSICAL COUNTED:</td>
                <td style="text-align: right; font-family: monospace; font-size: 16px; padding: 10px 6px;">₹{float(shift.actual_cash or 0.0):.2f}</td>
              </tr>
            </table>

            {f'<div style="background: #fef2f2; border: 1px solid #fecaca; padding: 10px; border-radius: 6px; margin-top: 12px; font-size: 13px; color: #991b1b;"><strong>Discrepancy Reason:</strong> {shift.difference_reason}</div>' if shift.difference_reason else ''}

            <h4 style="margin: 20px 0 8px 0; color: #1e3a8a; font-size: 14px; text-transform: uppercase;">Digital &amp; Total Shift Collections</h4>
            <table class="table">
              <tr><td>UPI / QR Collections:</td><td style="text-align: right; font-family: monospace;">₹{financials.get('upi_collections', 0):.2f}</td></tr>
              <tr><td>Card POS Collections:</td><td style="text-align: right; font-family: monospace;">₹{financials.get('card_collections', 0):.2f}</td></tr>
              <tr><td>Bank / Other:</td><td style="text-align: right; font-family: monospace;">₹{(financials.get('bank_collections', 0) + financials.get('other_collections', 0)):.2f}</td></tr>
              <tr style="font-weight: bold; background: #eff6ff; color: #1e3a8a;">
                <td style="padding: 10px 6px;">TOTAL REVENUE COLLECTED:</td>
                <td style="text-align: right; font-family: monospace; font-size: 16px; padding: 10px 6px;">₹{financials.get('total_collections', 0):.2f}</td>
              </tr>
            </table>
          </div>
          <div class="footer">
            Automated Audit Notification &bull; Generated by Lodge Management System
          </div>
        </div>
      </body>
    </html>
    """

def _send_notifications_worker(shift_id):
    """
    Background worker thread function for non-blocking email & WhatsApp delivery.
    """
    try:
        from apps.shifts.models import Shift
        shift = Shift.objects.select_related('user').get(id=shift_id)
        settings_obj = Settings.get_settings()
        financials = calculate_shift_financials(shift)

        summary_text = build_shift_summary_text(shift, settings_obj, financials)
        summary_html = build_shift_summary_html(shift, settings_obj, financials)

        # 1. Email Notifications
        if settings_obj.notify_shift_close_email:
            email_list = [e.strip() for e in (settings_obj.shift_alert_emails or "").split(',') if e.strip()]
            if not email_list and settings_obj.email:
                email_list = [settings_obj.email.strip()]

            if email_list:
                subject = f"[LMS Shift Alert] #{shift.shift_number} Closed - {settings_obj.lodge_name} ({shift.get_status_display()})"
                try:
                    send_mail(
                        subject=subject,
                        message=summary_text,
                        html_message=summary_html,
                        from_email=getattr(django_settings, 'DEFAULT_FROM_EMAIL', 'noreply@lodgemanagement.com'),
                        recipient_list=email_list,
                        fail_silently=False
                    )
                    logger.info(f"Shift closing email sent successfully for Shift #{shift.shift_number} to {email_list}")
                except Exception as mail_err:
                    logger.warning(f"Failed to deliver shift closing email: {mail_err}")

        # 2. WhatsApp Notifications
        if settings_obj.notify_shift_close_whatsapp:
            phone_list = [p.strip() for p in (settings_obj.shift_alert_phones or "").split(',') if p.strip()]
            if not phone_list and settings_obj.phone:
                phone_list = [settings_obj.phone.strip()]

            if settings_obj.whatsapp_api_url and phone_list:
                for phone in phone_list:
                    try:
                        payload = {
                            "phone": phone,
                            "message": summary_text,
                            "shift_number": shift.shift_number,
                            "api_key": settings_obj.whatsapp_api_key or ""
                        }
                        headers = {"Content-Type": "application/json"}
                        if settings_obj.whatsapp_api_key:
                            headers["Authorization"] = f"Bearer {settings_obj.whatsapp_api_key}"

                        requests.post(
                            settings_obj.whatsapp_api_url,
                            json=payload,
                            headers=headers,
                            timeout=5
                        )
                        logger.info(f"WhatsApp shift alert dispatched to {phone}")
                    except Exception as wa_err:
                        logger.warning(f"Failed to dispatch WhatsApp alert to {phone}: {wa_err}")
            else:
                logger.info(f"WhatsApp Shift Alert ready for dispatch to {phone_list}:\n{summary_text}")

    except Exception as e:
        logger.error(f"Error in _send_notifications_worker for shift {shift_id}: {e}", exc_info=True)

def trigger_shift_closing_notifications(shift):
    """
    Spawns a daemon thread to asynchronously dispatch notifications without blocking the API response.
    """
    thread = threading.Thread(target=_send_notifications_worker, args=(shift.id,), daemon=True)
    thread.start()
