# Generated by Django 6.0.5 on 2026-08-09 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='expected_checkout_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
