# Generated by Django 6.0.5 on 2026-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_check_in_time_booking_expected_checkout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='FIXED', max_length=20, null=True),
        ),
    ]
