# Generated by Django 6.0.5 on 2026-09-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_historicalroom_historicalroomdeletionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroomtype',
            name='catalogue_badge',
            field=models.CharField(blank=True, default='', help_text='Promotional chip e.g. Best Value, Most Popular, Luxury', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalroomtype',
            name='show_in_catalogue',
            field=models.BooleanField(default=True, help_text='Display this room type on the public digital catalogue'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='catalogue_badge',
            field=models.CharField(blank=True, default='', help_text='Promotional chip e.g. Best Value, Most Popular, Luxury', max_length=50),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='show_in_catalogue',
            field=models.BooleanField(default=True, help_text='Display this room type on the public digital catalogue'),
        ),
    ]
