# Generated by Django 6.0.5 on 2026-08-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=20, unique=True)),
                ('permissions', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser (Developer / SaaS Platform Owner)'), ('HOTEL_OWNER', 'Hotel Owner'), ('SUPER_ADMIN', 'Super Admin (Owner)'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist')], default='RECEPTIONIST', max_length=20),
        ),
    ]
