# Generated by Django 6.0.5 on 2026-08-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rolepermission_alter_user_role'),
        ('settings_app', '0008_remove_settings_daily_petty_cash_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Assigned lodge property for multi-tenant isolation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='settings_app.property'),
        ),
    ]
