# Generated by Django 6.0.5 on 2026-09-05 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_property'),
        ('settings_app', '0010_alter_propertysubscription_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Hotel property this permission matrix applies to (or null for global defaults)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='settings_app.property'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'property'), name='unique_role_property'),
        ),
    ]
