# Generated by Django 6.0.5 on 2026-09-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rolepermission_property_alter_rolepermission_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_use_mobile_app',
            field=models.BooleanField(default=True, help_text='Designates whether this user is allowed to access the mobile application.'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Custom permissions overriding role defaults for this specific user'),
        ),
    ]
